
SHELL	=	SH

# プロジェクト名（生成されるファイル名）
NAME	=	ReversiAdv

# プロジェクトで使用するアセンブラファイル
.SFILES	=	crt0.S

# プロジェクトで使用するＣ言語ファイル
#.CFILES	=	main.c ReversiEngine.c
.CFILES	=	ReversiMain.c ReversiOpening.c ReversiColorSelect.c ReversiLevelSelect.c ReversiGame.c ReversiEngine.c
#.CFILES	=	ReversiOpening.c


# オブジェクトファイル
.OFILES	=	$(.SFILES:.s=.o) $(.CFILES:.c=.o)

# アセンブル時フラグ
ASFLAGS	=	-mthumb-interwork

# コンパイル時フラグ
CFLAGS	=	-g -O3 -mthumb-interwork \
		-nostdlib -Wall -fverbose-asm -fpeephole

# リンク時フラグ
LDFLAGS	 =	-Map $(MAPFILE) \
#		-Ttext 0x08000000 -Tbss 0x03000000 \
		-Ttext 0x02000000 -Tbss 0x03000000 \
		-Wall -mthumb-interwork 
		
# 生成されるファイル名
DEPENDFILE	=	Makedepend.txt
MAPFILE		=	$(NAME).map
TARGET_ELF	=	$(NAME).elf
TARGET_BIN	=	$(NAME).mb.gba


# コンパイル・リンクする過程

$(TARGET_BIN): $(TARGET_ELF)
	objcopy -v -O binary $< $@

$(TARGET_ELF): $(.OFILES) Makefile.txt $(.AFILES) $(DEPENDFILE)
	@echo > $(MAPFILE)
	$(CC) -g -o $@ $(.OFILES) -Wl,$(LDFLAGS)

.PHONY: all clean depend data

all:	clean depend data $(TARGET_BIN)

clean:
	-rm $(.OFILES) $(DEPENDFILE)
clean_data:
	$(foreach .ADIR_TMP, $(dir $(.AFILES)), make -C $(.ADIR_TMP) clean;)

depend:
	$(CC) $(CFLAGS) -M $(.CFILES) > $(DEPENDFILE)

$(DEPENDFILE): 
	$(CC) $(CFLAGS) -M $(.CFILES) > $(DEPENDFILE)

.SUFFIXES: .s .c .o .a


